---

# apt_key task below replaced with an equivalen shell task due to bug described
# in https://github.com/ansible/ansible/issues/9966

#- name: Download and install nodejs apt public signing key
#  apt_key:
#    url: "{{ nodejs_signing_key_url }}"
#    state: present

- name: Download and install nodejs apt public signing key
  shell:
      apt-key list | grep nodesource || \
        wget -qO- https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -

- name: Add nodejs apt repository definition to apt sources list
  template:
    src:   nodesource.list.j2
    dest:  /etc/apt/sources.list.d/nodesource.list
    owner: root
    group: root
    mode:  0644
  register: repo

- name: Update nodejs apt repos
  apt: update_cache=yes
  when: repo is changed

- name: Install nodejs
  apt:
    name: nodejs={{ nodejs_package_version }}
    update_cache: yes
    state: present

- name: Install nodejs build tools
  apt:
    name: build-essential
    state: present
  when: nodejs_build_tools_install|default(true)
